import{a as u,S as m,i as d}from"./assets/vendor-56025df1.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerpolicy&&(n.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?n.credentials="include":e.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(e){if(e.ep)return;e.ep=!0;const n=a(e);fetch(e.href,n)}})();const r={input:document.querySelector('[type="text"]'),searchBtn:document.querySelector('[type="submit"]'),gallery:document.querySelector(".gallery"),loadBtn:document.querySelector(".js-load"),loadDiv:document.querySelector(".js-loader")},g={API_KEY:"41488002-513c6a9a4c115eae6a99045d3"};u.defaults.baseURL="https://pixabay.com/api/";let s=1;const c=40;let p=new m(".gallery a");async function f(o=s){return await u.get(`?key=${g.API_KEY}&q=${r.input.value}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${c}`).then(a=>a.data).catch(a=>console.error(a))}r.searchBtn.addEventListener("click",v);r.loadBtn.addEventListener("click",L);function v(o){if(o.preventDefault(),s=1,r.input.value.trim()==="")return d.error({message:"Sorry, the field must be filled in!",position:"topRight"});r.gallery.innerHTML='<span class="loader"></span>',f().then(t=>{r.gallery.innerHTML=h(t.hits),p.refresh(),c>=t.totalHits?r.loadBtn.hidden=!0:r.loadBtn.hidden=!1}).catch(t=>console.error(t))}function L(o){o.preventDefault(),s+=1,r.loadDiv.innerHTML='<span class="loader"></span>',r.loadBtn.hidden=!0,f(s).then(t=>{if(r.gallery.insertAdjacentHTML("beforeend",h(t.hits)),p.refresh(),t.totalHits/c<=s)return r.loadBtn.hidden=!0,r.loadDiv.innerHTML="",d.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});t.totalHits/c>=s&&(r.loadDiv.innerHTML="",r.loadBtn.hidden=!1);let i=document.querySelector(".gallery-item").getBoundingClientRect();scrollBy({top:i.height*3,behavior:"smooth"})})}function h(o){return o.length===0&&d.error({message:"Sorry, there are no images matching <br> your search query. Please try again!",position:"topRight"}),o.map(({webformatURL:t,largeImageURL:a,tags:i,likes:e,views:n,comments:l,downloads:y})=>`
    <li class='gallery-item'>
        <a href='${a}'>
            <img src="${t}" alt="${i}" data-source=${a} class='gallery-img'/>
        </a>
        <div class='text-container'>
            <p>Likes<span>${e}</span></p>
            <p>Views<span>${n}</span></p>
            <p>Comments<span>${l}</span></p>
            <p>Downloads<span>${y}</span></p>
        </div>
    </li>`).join("")}
//# sourceMappingURL=commonHelpers.js.map
