import{S as L,a as d,i as w}from"./assets/vendor-56025df1.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();function u(){w.show({close:!1,closeOnClick:!0,message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",timeout:3e3,transitionIn:"flipInX",transitionOut:"flipOutX",position:"topRight",backgroundColor:"red",progressBar:!1})}let b=new L("#gallery a",{overlayOpacity:.5,showCounter:!1});const m=document.querySelector(".search-form"),p=document.querySelector(".search-input"),f=document.querySelector(".gallery"),n=document.querySelector(".loader"),l=document.querySelector(".load-more-btn");let c=1;m.addEventListener("submit",k);l.addEventListener("click",q);async function k(r){n.classList.remove("hide"),f.innerHTML="",l.classList.add("hide"),r.preventDefault(),c=1;try{const o=(await d.get("https://pixabay.com/api/",{params:{key:"41488002-513c6a9a4c115eae6a99045d3",q:p.value,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:c}})).data.hits;setTimeout(()=>{if(n.classList.add("hide"),o.length===0)return u();h(o),g()},2e3)}catch(s){console.error(s)}m.reset()}function h(r){f.innerHTML=r.reduce((s,{webformatURL:o,largeImageURL:i,tags:e,likes:t,views:a,comments:y,downloads:v})=>s+`
      <li class="gallery-item">
        <a href="${i}">
          <img src="${o}" alt="${e}" />
        </a>
        <div class="image-desc">
          <div class="container-link">Likes <span class="container-item">${t}</span></div>
          <div class="container-link">Views <span class="container-item">${a}</span></div>
          <div class="container-link">Comments <span class="container-item">${y}</span></div>
          <div class="container-link">Downloads <span class="container-item">${v}</span></div>
        </div>
      </li>
      `,""),b.refresh()}function g(){l.classList.remove("hide")}async function q(){n.classList.remove("hide"),l.classList.add("hide"),c++;try{const s=(await d.get("https://pixabay.com/api/",{params:{key:"41488002-513c6a9a4c115eae6a99045d3",q:p.value,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:c}})).data.hits;setTimeout(()=>{if(n.classList.add("hide"),s.length===0)return u();h(s),g()},2e3)}catch(r){console.error(r)}}
//# sourceMappingURL=commonHelpers.js.map
