import{a as d,S as m,i as c}from"./assets/vendor-56025df1.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerpolicy&&(o.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?o.credentials="include":t.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const r={input:document.querySelector('[type="text"]'),searchBtn:document.querySelector('[type="submit"]'),gallery:document.querySelector(".gallery"),loadBtn:document.querySelector(".js-load"),loadDiv:document.querySelector(".js-loader")},y={API_KEY:"41488002-513c6a9a4c115eae6a99045d3"};d.defaults.baseURL="https://pixabay.com/api/";let i=1;const u=40;let p=new m(".gallery a");async function f(n=i){try{return(await d.get(`?key=${y.API_KEY}&q=${r.input.value}&image_type=photo&orientation=horizontal&safesearch=true&page=${n}&per_page=${u}`)).data}catch(e){console.error(e)}}r.searchBtn.addEventListener("click",L);r.loadBtn.addEventListener("click",v);function L(n){if(n.preventDefault(),i=1,r.input.value.trim()==="")return c.error({message:"Sorry, the field must be filled in!",position:"topRight"});r.gallery.innerHTML='<span class="loader"></span>',f().then(e=>{r.gallery.innerHTML=h(e.hits),p.refresh(),c.info({message:`Total Hits: ${e.totalHits}, Loaded Files: ${e.hits.length}`,position:"topRight"}),u>=e.totalHits?r.loadBtn.hidden=!0:r.loadBtn.hidden=!1}).catch(e=>console.error(e))}function v(n){n.preventDefault(),i+=1,r.loadDiv.innerHTML='<span class="loader"></span>',r.loadBtn.hidden=!0,f(i).then(e=>{if(r.gallery.insertAdjacentHTML("beforeend",h(e.hits)),p.refresh(),c.info({message:`Loaded Files: ${e.hits.length}`,position:"topRight"}),e.totalHits/u<=i)return r.loadBtn.hidden=!0,r.loadDiv.innerHTML="",c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});e.totalHits/u>=i&&(r.loadDiv.innerHTML="",r.loadBtn.hidden=!1);let s=document.querySelector(".gallery-item").getBoundingClientRect();scrollBy({top:s.height*3,behavior:"smooth"})})}function h(n){return n.length===0&&c.error({message:"Sorry, there are no images matching <br> your search query. Please try again!",position:"topRight"}),n.map(({webformatURL:e,largeImageURL:a,tags:s,likes:t,views:o,comments:l,downloads:g})=>`
    <li class='gallery-item'>
        <a href='${a}'>
            <img src="${e}" alt="${s}" data-source=${a} class='gallery-img'/>
        </a>
        <div class='text-container'>
            <p>Likes<span>${t}</span></p>
            <p>Views<span>${o}</span></p>
            <p>Comments<span>${l}</span></p>
            <p>Downloads<span>${g}</span></p>
        </div>
    </li>`).join("")}
//# sourceMappingURL=commonHelpers.js.map
